live_config_reload = true

import = [
    "~/.config/alacritty/carbonfox.toml"
]

[font]
size = 18.0

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Shift|Control"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[window]
dynamic_title = true
startup_mode = "Fullscreen"
option_as_alt = "Both"
